// <auto-generated />
using System;
using BankMlekaBackendApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankMlekaBackendApp.Migrations
{
    [DbContext(typeof(BankMlekaContext))]
    [Migration("20260607122615_InitialAuth")]
    partial class InitialAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankMlekaBackendApp.Models.BabyInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("1.jpg")
                        .HasColumnName("avatar_name");

                    b.Property<int?>("FatherId")
                        .HasColumnType("int")
                        .HasColumnName("father_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("gender")
                        .IsFixedLength();

                    b.Property<double?>("Height")
                        .HasColumnType("float")
                        .HasColumnName("height");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<int?>("MotherId")
                        .HasColumnType("int")
                        .HasColumnName("mother_id");

                    b.Property<string>("Pesel")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("pesel");

                    b.Property<double?>("Weight")
                        .HasColumnType("float")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("PK__baby_inf__3213E83F573F049F");

                    b.HasIndex("FatherId");

                    b.HasIndex("MotherId");

                    b.ToTable("baby_info", (string)null);
                });

            modelBuilder.Entity("BankMlekaBackendApp.Models.BabyUpdate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BabyId")
                        .HasColumnType("int")
                        .HasColumnName("baby_id");

                    b.Property<double?>("Consumption")
                        .HasColumnType("float")
                        .HasColumnName("consumption");

                    b.Property<double?>("Height")
                        .HasColumnType("float")
                        .HasColumnName("height");

                    b.Property<DateOnly?>("UpdateDate")
                        .HasColumnType("date")
                        .HasColumnName("update_date");

                    b.Property<double?>("Weight")
                        .HasColumnType("float")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("PK__baby_upd__3213E83F1CE88693");

                    b.HasIndex("BabyId");

                    b.ToTable("baby_updates", (string)null);
                });

            modelBuilder.Entity("BankMlekaBackendApp.Models.Bed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BedNumber")
                        .HasColumnType("int")
                        .HasColumnName("bed_number");

                    b.Property<int>("Floor")
                        .HasColumnType("int")
                        .HasColumnName("floor");

                    b.Property<int>("Room")
                        .HasColumnType("int")
                        .HasColumnName("room");

                    b.HasKey("Id")
                        .HasName("PK__beds__3213E83F21AF54EC");

                    b.ToTable("beds", (string)null);
                });

            modelBuilder.Entity("BankMlekaBackendApp.Models.Bedding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AssignDate")
                        .HasColumnType("date")
                        .HasColumnName("assign_date");

                    b.Property<int>("BabyId")
                        .HasColumnType("int")
                        .HasColumnName("baby_id");

                    b.Property<int>("BedId")
                        .HasColumnType("int")
                        .HasColumnName("bed_id");

                    b.Property<int>("MotherId")
                        .HasColumnType("int")
                        .HasColumnName("mother_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.HasKey("Id")
                        .HasName("PK__beddings__3213E83F24B16625");

                    b.HasIndex("BabyId");

                    b.HasIndex("BedId");

                    b.HasIndex("MotherId");

                    b.ToTable("beddings", (string)null);
                });

            modelBuilder.Entity("BankMlekaBackendApp.Models.Consumption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<int>("BabyId")
                        .HasColumnType("int")
                        .HasColumnName("baby_id");

                    b.Property<int>("MilkId")
                        .HasColumnType("int")
                        .HasColumnName("milk_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("PK__consumpt__3213E83F7355E328");

                    b.HasIndex("BabyId");

                    b.HasIndex("MilkId");

                    b.ToTable("consumption", (string)null);
                });

            modelBuilder.Entity("BankMlekaBackendApp.Models.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcceptanceDate")
                        .HasColumnType("datetime")
                        .HasColumnName("acceptance_date");

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("ExpectedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("expected_date");

                    b.Property<int?>("MilkId")
                        .HasColumnType("int")
                        .HasColumnName("milk_id");

                    b.Property<int>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<string>("TransportType")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("transport_type");

                    b.HasKey("Id")
                        .HasName("PK__delivery__3213E83F99D1DCF3");

                    b.HasIndex("DeviceId");

                    b.HasIndex("MilkId");

                    b.HasIndex("ParentId");

                    b.ToTable("delivery", (string)null);
                });

            modelBuilder.Entity("BankMlekaBackendApp.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxAmount")
                        .HasColumnType("int")
                        .HasColumnName("max_amount");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("PK__devices__3213E83F619ED9A8");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("BankMlekaBackendApp.Models.MilkInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcceptanceDate")
                        .HasColumnType("datetime")
                        .HasColumnName("acceptance_date");

                    b.Property<int>("BottleId")
                        .HasColumnType("int")
                        .HasColumnName("bottle_id");

                    b.Property<int>("DonorId")
                        .HasColumnType("int")
                        .HasColumnName("donor_id");

                    b.Property<int>("LastTestId")
                        .HasColumnType("int")
                        .HasColumnName("last_test_id");

                    b.Property<int>("MaxVolume")
                        .HasColumnType("int")
                        .HasColumnName("max_volume");

                    b.Property<string>("Storage")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("storage");

                    b.Property<DateTime>("TerminationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("termination_date");

                    b.Property<int>("Volume")
                        .HasColumnType("int")
                        .HasColumnName("volume");

                    b.HasKey("Id")
                        .HasName("PK__milk_inf__3213E83F97A30FCA");

                    b.HasIndex("DonorId");

                    b.HasIndex("LastTestId");

                    b.ToTable("milk_info", (string)null);
                });

            modelBuilder.Entity("BankMlekaBackendApp.Models.MilkTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Calories")
                        .HasColumnType("float")
                        .HasColumnName("calories");

                    b.Property<double>("Carbs")
                        .HasColumnType("float")
                        .HasColumnName("carbs");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("DonorId")
                        .HasColumnType("int")
                        .HasColumnName("donor_id");

                    b.Property<double>("Fat")
                        .HasColumnType("float")
                        .HasColumnName("fat");

                    b.Property<double>("Protein")
                        .HasColumnType("float")
                        .HasColumnName("protein");

                    b.HasKey("Id")
                        .HasName("PK__milk_tes__3213E83F7C84B7E8");

                    b.HasIndex("DonorId");

                    b.ToTable("milk_test", (string)null);
                });

            modelBuilder.Entity("BankMlekaBackendApp.Models.ParentInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("DonorStatus")
                        .HasColumnType("bit")
                        .HasColumnName("donor_status");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("gender")
                        .IsFixedLength();

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Pesel")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("pesel");

                    b.HasKey("Id")
                        .HasName("PK__parent_i__3213E83F4FE68BE4");

                    b.ToTable("parent_info", (string)null);
                });

            modelBuilder.Entity("BankMlekaBackendApp.Models.Rented", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    b.Property<DateOnly>("RentDate")
                        .HasColumnType("date")
                        .HasColumnName("rent_date");

                    b.Property<DateOnly?>("ReturnDate")
                        .HasColumnType("date")
                        .HasColumnName("return_date");

                    b.Property<int>("TransportId")
                        .HasColumnType("int")
                        .HasColumnName("transport_id");

                    b.HasKey("Id")
                        .HasName("PK__rented__3213E83F13B87B9A");

                    b.HasIndex("DeviceId");

                    b.HasIndex("TransportId");

                    b.ToTable("rented", (string)null);
                });

            modelBuilder.Entity("BankMlekaBackendApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("PK__users__3213E83F");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BankMlekaBackendApp.Models.BabyInfo", b =>
                {
                    b.HasOne("BankMlekaBackendApp.Models.ParentInfo", "Father")
                        .WithMany("BabyInfoFathers")
                        .HasForeignKey("FatherId")
                        .HasConstraintName("FK__baby_info__fathe__4D94879B");

                    b.HasOne("BankMlekaBackendApp.Models.ParentInfo", "Mother")
                        .WithMany("BabyInfoMothers")
                        .HasForeignKey("MotherId")
                        .HasConstraintName("FK__baby_info__mothe__4CA06362");

                    b.Navigation("Father");

                    b.Navigation("Mother");
                });

            modelBuilder.Entity("BankMlekaBackendApp.Models.BabyUpdate", b =>
                {
                    b.HasOne("BankMlekaBackendApp.Models.BabyInfo", "Baby")
                        .WithMany("BabyUpdates")
                        .HasForeignKey("BabyId")
                        .IsRequired()
                        .HasConstraintName("FK__baby_upda__baby___5070F446");

                    b.Navigation("Baby");
                });

            modelBuilder.Entity("BankMlekaBackendApp.Models.Bedding", b =>
                {
                    b.HasOne("BankMlekaBackendApp.Models.BabyInfo", "Baby")
                        .WithMany("Beddings")
                        .HasForeignKey("BabyId")
                        .IsRequired()
                        .HasConstraintName("FK__beddings__baby_i__5629CD9C");

                    b.HasOne("BankMlekaBackendApp.Models.Bed", "Bed")
                        .WithMany("Beddings")
                        .HasForeignKey("BedId")
                        .IsRequired()
                        .HasConstraintName("FK__beddings__bed_id__5535A963");

                    b.HasOne("BankMlekaBackendApp.Models.ParentInfo", "Mother")
                        .WithMany("Beddings")
                        .HasForeignKey("MotherId")
                        .IsRequired()
                        .HasConstraintName("FK__beddings__mother__571DF1D5");

                    b.Navigation("Baby");

                    b.Navigation("Bed");

                    b.Navigation("Mother");
                });

            modelBuilder.Entity("BankMlekaBackendApp.Models.Consumption", b =>
                {
                    b.HasOne("BankMlekaBackendApp.Models.BabyInfo", "Baby")
                        .WithMany("Consumptions")
                        .HasForeignKey("BabyId")
                        .IsRequired()
                        .HasConstraintName("FK__consumpti__baby___60A75C0F");

                    b.HasOne("BankMlekaBackendApp.Models.MilkInfo", "Milk")
                        .WithMany("Consumptions")
                        .HasForeignKey("MilkId")
                        .IsRequired()
                        .HasConstraintName("FK__consumpti__milk___619B8048");

                    b.Navigation("Baby");

                    b.Navigation("Milk");
                });

            modelBuilder.Entity("BankMlekaBackendApp.Models.Delivery", b =>
                {
                    b.HasOne("BankMlekaBackendApp.Models.Device", "Device")
                        .WithMany("Deliveries")
                        .HasForeignKey("DeviceId")
                        .IsRequired()
                        .HasConstraintName("FK__delivery__device__6754599E");

                    b.HasOne("BankMlekaBackendApp.Models.MilkInfo", "Milk")
                        .WithMany("Deliveries")
                        .HasForeignKey("MilkId")
                        .HasConstraintName("FK__delivery__milk_i__68487DD7");

                    b.HasOne("BankMlekaBackendApp.Models.ParentInfo", "Parent")
                        .WithMany("Deliveries")
                        .HasForeignKey("ParentId")
                        .IsRequired()
                        .HasConstraintName("FK__delivery__parent__66603565");

                    b.Navigation("Device");

                    b.Navigation("Milk");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("BankMlekaBackendApp.Models.MilkInfo", b =>
                {
                    b.HasOne("BankMlekaBackendApp.Models.ParentInfo", "Donor")
                        .WithMany("MilkInfos")
                        .HasForeignKey("DonorId")
                        .IsRequired()
                        .HasConstraintName("FK__milk_info__donor__5CD6CB2B");

                    b.HasOne("BankMlekaBackendApp.Models.MilkTest", "LastTest")
                        .WithMany("MilkInfos")
                        .HasForeignKey("LastTestId")
                        .IsRequired()
                        .HasConstraintName("FK__milk_info__last___5DCAEF64");

                    b.Navigation("Donor");

                    b.Navigation("LastTest");
                });

            modelBuilder.Entity("BankMlekaBackendApp.Models.MilkTest", b =>
                {
                    b.HasOne("BankMlekaBackendApp.Models.ParentInfo", "Donor")
                        .WithMany("MilkTests")
                        .HasForeignKey("DonorId")
                        .IsRequired()
                        .HasConstraintName("FK__milk_test__donor__59FA5E80");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("BankMlekaBackendApp.Models.Rented", b =>
                {
                    b.HasOne("BankMlekaBackendApp.Models.Device", "Device")
                        .WithMany("Renteds")
                        .HasForeignKey("DeviceId")
                        .IsRequired()
                        .HasConstraintName("FK__rented__device_i__6B24EA82");

                    b.HasOne("BankMlekaBackendApp.Models.Delivery", "Transport")
                        .WithMany("Renteds")
                        .HasForeignKey("TransportId")
                        .IsRequired()
                        .HasConstraintName("FK__rented__transpor__6C190EBB");

                    b.Navigation("Device");

                    b.Navigation("Transport");
                });

            modelBuilder.Entity("BankMlekaBackendApp.Models.BabyInfo", b =>
                {
                    b.Navigation("BabyUpdates");

                    b.Navigation("Beddings");

                    b.Navigation("Consumptions");
                });

            modelBuilder.Entity("BankMlekaBackendApp.Models.Bed", b =>
                {
                    b.Navigation("Beddings");
                });

            modelBuilder.Entity("BankMlekaBackendApp.Models.Delivery", b =>
                {
                    b.Navigation("Renteds");
                });

            modelBuilder.Entity("BankMlekaBackendApp.Models.Device", b =>
                {
                    b.Navigation("Deliveries");

                    b.Navigation("Renteds");
                });

            modelBuilder.Entity("BankMlekaBackendApp.Models.MilkInfo", b =>
                {
                    b.Navigation("Consumptions");

                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("BankMlekaBackendApp.Models.MilkTest", b =>
                {
                    b.Navigation("MilkInfos");
                });

            modelBuilder.Entity("BankMlekaBackendApp.Models.ParentInfo", b =>
                {
                    b.Navigation("BabyInfoFathers");

                    b.Navigation("BabyInfoMothers");

                    b.Navigation("Beddings");

                    b.Navigation("Deliveries");

                    b.Navigation("MilkInfos");

                    b.Navigation("MilkTests");
                });
#pragma warning restore 612, 618
        }
    }
}
